### ISSUE TITLE
PersistentDataContainer

### ISSUE THREAD

**Issue by kennytv** [PaperMC/docs#107]

**Comment by Machine-Maker** [comment]
There should be a big emphasis, perhaps even a redirect link for a custom enchants guide to this. PDC should be used for all custom enchantments (along with adding lore lines). We should heavily discourage any attempt to register custom enchants through a completely unsupported system.

**Comment by Machine-Maker** [comment]
Part of this was handled in a4e4b82d2fec686470b41e492d19ea1cade4394e but not the part about emphasizing its use for enchantments. Perhaps there should be a separate guide for custom enchantments that just gives examples of it using PDC? instead of having it on the PDC page itself.

**Comment by olijeffers0n** [comment]
Ah, didn't see this issue when making my PR... 

It probably does not belong on **the** PDC page though, as it was intended as a guide to the PDC and not a specific use of it 🤷

**Comment by Machine-Maker** [comment]
Yeah, I agree. I'll close this issue and then open another one with a custom enchantments guide.
