### ISSUE TITLE
Documentation organisation and replacements

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/docs#12]
Been meaning to create an issue for this for a while, people with write access here are asked to maybe clean up this issue and maybe create sub-issues, etc; There has been a few small talks about this internally but I feel that a more public/documentated discussion would be ideal and maybe aid in finding help to accomplish this

A key aspect of our documentation is that we still heavily rely on the documentation elsewhere, e.g. the bukkit wiki, the spigot wiki, for a large part of our documentation

While this has worked well in the past, it leaves a lot of stuff lacking or missing, ref: PaperMC/docs#20 and PaperMC/docs#22 for example, especially post hard fork, we are going to need to consider the duplication of this documentation in order to offer a more central replacement

A few key examples are, as above, commands.yml, but, also, changes to spigot.yml, added permissions, etc, as well as many pieces of documentation such as the firewall guide on spigot which offers flawed recommendations for plugins. A big thing is that I question if we'd be really better off moving towards a real wiki for this, given that it's more accessible for people who aren't developers vs working with the niche restructured text format.

hard fork plans do offer some concerns to the existing documentation and our reliance of info elsewhere, e.g. hardforking gives us the chance to heavily re-organise the configuration layout for a well needed clean up and organisation, which does put some questions around documentation there, especially as I feel that the current layout of the config docs is somewhat unwieldy at times

I also feel that the current layout of documentation isn't exactly ideal, I've done a bit of work on this on the past, but, expanding on the documentation as is feels a bit icky due to the current layout, I've wanted to do more on this but this would impact existing PRs of which my involvement with this repo is somewhat limited for various reasons (health, time, more productive working on code...)

I think a public discussion on this would likely be ideal as we can determine a goal for this or at least discuss plans going forward, does a real wiki (with limited registration for spam/quality reasons) make a much better sense long term?

**Comment by sulu5890** [comment]
We are here. A lot more discussion in the `#docs` channel on our [discord](https://discord.gg/papermc).
