### ISSUE TITLE
Page for listing all bundled dependencies

### ISSUE THREAD

**Issue by Andre601** [PaperMC/docs#150]
The Paper docs should have a page for developers that lists all dependencies that are included within Paper's API for a developer to access and use.

It would help in keeping the jar file small by knowing what libraries are present and provided and which need to be included, either by shading in or by using the PluginLoader itself.

It can also help answer questions like "Is this dependency included?" which I myself had recently regarding the Adventure Legacy Serializer.

Wanted to open this issue first before Blatantly opening a PR, to see if there is a need for it and to discuss a possible design for the page.

**Comment by electronicboy** [comment]
unless somebody writes a script to automate this to list deps + versions, etc, honestly,no; you generally shouldn't rely on something being bundled outside of what's exposed in the API, and even there it's shaky given how much outdated crud exists

**Comment by Andre601** [comment]
> unless somebody writes a script to automate this to list deps + versions, etc, honestly,no; you generally shouldn't rely on something being bundled outside of what's exposed in the API, and even there it's shaky given how much outdated crud exists

The point is more to have some clarity.
Like devs may include a library because they don't know that paper includes and exposes one, so it's useless extra bloat that really isn't needed.

At the very least could the more popular choices like Gson, Adventure, Guave, etc. be listed... Not every single one right now.

Also, does Paper *really* update and add new libs that frequently? I really have my doubts about this tbh...

**Comment by electronicboy** [comment]
issue comes in is that nobody generally cares to update this kind of stuff cos it's easily forgettable, and then you lose the relevancy of the page; We update adventure as and when we can, which is fairly frequently as adventure releases, the rest are already exposed as artifacts through your IDE and generally easy to see

hence why I'd want a script or something, cos at least then it's a 2 second run a grade task or whatever and copy over the info, rather than hoping people track the changes or have to go through the list, humans are lazy and all

**Comment by Machine-Maker** [comment]
Both maven and gradle have commands to show the dependency tree and what libraries are exposed transitively. If devs don't use that, what makes you think they'd use this instead?

**Comment by Machine-Maker** [comment]
I'm gonna close this as not planned. Generally, there are way better places to discover what dependencies are included transitively through the API, and a docs page here would just be a less-accurate version of those.
