### ISSUE TITLE
Tabs do not work on Velocity's "Creating Your First Plugin" page

### ISSUE THREAD

**Issue by mudkipdev** [PaperMC/docs#166]
https://docs.papermc.io/velocity/dev/creating-your-first-plugin
https://github.com/PaperMC/docs/blob/main/docs/velocity/dev/getting-started/creating-your-first-plugin.md

The problematic lines:
```
import Tabs from "@theme/Tabs";
import TabItem from "@theme/TabItem";
```

**Comment by olijeffers0n** [comment]
Can be closed. Addressed in 8b46cda
