### ISSUE TITLE
want help with getting rid of anti xray for my admins who use spectator 

### ISSUE THREAD

**Issue by Robo5626** [PaperMC/docs#178]
i want to remove anti xray for spectators is there a way to do that because my admins are complaining about it

**Comment by electronicboy** [comment]
No, but what you can do is use the override perm to do that; do note that they'd need to move away from the existing area in order for chunks to be sent without obfuscation

**Comment by Robo5626** [comment]
how do i override that

**Comment by Robo5626** [comment]
i did that enabled the perm for me and it still does it even in new chunks

**Comment by MiniDigger** [comment]
please come to our discord for support, #paper-help
