### ISSUE TITLE
Reference CONTRIBUTING.md in Contributing docs 

### ISSUE THREAD

**Issue by notTamion** [PaperMC/docs#251]
Since the CONTRIBUTING.md file in the Paper repository is the main source for information on contributing i think referencing or featuring it in the docs would be a good idea.

**Comment by olijeffers0n** [comment]
The paper contributing file is very different to docs. That included a lot of information about the patch system which isn’t used here. We also care a lot more about grammar and formatting here as well. I’m going to close this but feel free to say if you feel otherwise.
