### ISSUE TITLE
Configuration Component Agolia Crawler Selector for the URL

### ISSUE THREAD

**Issue by olijeffers0n** [PaperMC/docs#268]
The Agolia Crawler currently only allows you to navigate to the page a particular search result is on when it is a node within the Configuration component. This should allow you to navigate correctly by setting the `url` tag properly. 

```js
return helpers.docsearch({
  recordProps: {
    lvl0: {
      selectors: "",
      defaultValue: lvl0,
    },
    url: {
      selectors: "",
      defaultValue: url.toString(),
    },
    lvl1: "h1",
    lvl2: "article h2",
    lvl3: "article h3",
    lvl4: "article h4",
    lvl5: "article h5, article td:first-child",
    lvl6: "article h6",
    content:
      "article p, article li, article td:last-child, article button.with-value",
  },
});
```

This is how you can override the URL tag, however, I do not know how to access the anchor tag for this item. You do have access to a Cheerio instance which might be possible to use, however I cannot think of anything currently.

**Comment by Machine-Maker** [comment]
So can't you use the cheerio instance to get the href for the a tag? then make that the url. 
<img width="821" alt="image" src="https://github.com/PaperMC/docs/assets/15055071/18e31c02-ece3-4e93-b774-5cb131e9fe84">
