### ISSUE TITLE
Aikar's Flags don't match the Start Script Generator

### ISSUE THREAD

**Issue by Darwin1546** [PaperMC/docs#298]
There is a section in https://docs.papermc.io/paper/aikars-flags, that says if you has 12G+ memory, you should adjust flags a little.  

Script Generator completely skips that part and just pastes static flags.  

> ![изображение](https://github.com/PaperMC/docs/assets/63585283/7f02a8f1-6717-4851-844c-728ee0138f0d)

**Comment by Nacioszeczek** [comment]
I'll change it to an issue about the Aikar's flags themselves, not the generator [based on this](https://canary.discord.com/channels/289587909051416579/947676006964162611/1194196304650326058) and leave it for @olijeffers0n to decide.
Thanks for the report nonetheless.
