### ISSUE TITLE
Is it possible to disable the GUI option by default when Server Configuration uses Velocity Flags?

### ISSUE THREAD

**Issue by BangXi** [PaperMC/docs#302]
Is it possible to disable the GUI option by default when Server Configuration uses Velocity Flags?
![9244f60e-c918-4e35-b14c-d3dc65f6992b(1)](https://github.com/PaperMC/docs/assets/135555687/c38c9ff8-b041-456d-b8bf-2cf6e35dedd8)
boom

**Comment by Nacioszeczek** [comment]
Yeah this flag shouldn't be added when Velocity is selected as Velocity will not start then
cc @olijeffers0n

**Comment by olijeffers0n** [comment]
Thanks
