### ISSUE TITLE
favicon.ico not found on docs page

### ISSUE THREAD

**Issue by Joo200** [PaperMC/docs#304]
Somehow the favicon is not visible/not found from Firefox. The network analyze tool indicates a wrong search location for the favicon.ico: `https://docs.papermc.io/img/favicon.ico` - the favicon.ico can be found in `https://docs.papermc.io/favicon.ico`.

This bug is not reproducable on Chrome and Chrome based browsers because they use the icon-144x144.png (or smaller pngs) in the img directory.

**Comment by MiniDigger** [comment]
ooops, wanted to do a PR, oh well
