### ISSUE TITLE
Add onboarding page

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/docs#318]
Crossref for https://github.com/PaperMC/Paper/pull/10312

We should have a page which serves to get new server owners into some level of swing, this will mostly be a point of leading server owners to more dedicated guides in a friendly manner, but, may also decide to contain some general recommendations, i.e. how to whitelist, for example.

Not 100% sure what a good onboarding page would contain, however, that is probably a discussion point here

**Comment by Leguan16** [comment]
Some things that came into my mind:
- Whitelist
- Optimisation 
- Maybe some thing about permissions?
- how to add plugins
- mention port forwarding and maybe ref to another external site
- useful commands

**Comment by EterNityCH** [comment]
This could be a decent idea as long as the page is kept simple and easy to follow and serve as a starting point for someone completely new. 

 Contribution is always welcomed; however, it is always good to communicate via Discord with our maintainers before proceeding to avoid doing extra work.


- How to use whitelist features 
- How to use basic command such as OP and gamerules with reference to official Minecraft wiki. 
- How to add and update plugins 
- How to update Paper versions
- Perform basic backups. 
- Config options that a typical server owner may be interested in changing (frequently asked in paper-help) such as the one mentioned here https://paper-chan.moe/paper/
- An optimization guide is essentially an opinionated piece, so I would be cautious before making any official suggestions. I believe that, if anything, we should encourage new server owners to seek help on our wonderful Discord so they can receive proper directions and guidance as needed.
