### ISSUE TITLE
Adding a clarification to PDC on copying data.

### ISSUE THREAD

**Issue by NinjaMandalorian** [PaperMC/docs#476]
A quality of life improvement for developers, adding a note that specifies data is **not automatically** copied over for you would help with confusion.

Following the components update, the source ItemStack components (including PublicBukkitValues) are copied to the "components" section of a placed block entity, but the PDC is not copied _to_ the block entity itself.

This can be deceiving, as with commands such as `/data` it appears the data is carried across to a TileState, when it is not.
![image](https://github.com/user-attachments/assets/595ef846-13db-464b-949b-09494b1d24da)

This particular instance caused myself and others significant confusion, leading to the suggestion of creating a small InfoBox/WarningBox [here](https://docs.papermc.io/paper/dev/pdc#storing-on-different-objects) clarifying that "Data is not copied across for you, and needs to be manually set the keys if 'moving' between PersistentDataHolders."

**Comment by Machine-Maker** [comment]
Yeah, that does seem to be a common misconception, that itemstacks that create block entities have multiple pdcs, one for the stack, and you can access the block entity's PDC from that stack as well.

**Comment by NinjaMandalorian** [comment]
Sounds good, I'll work on the PR now.

**Comment by NinjaMandalorian** [comment]
Closed by #477
